/*!
 * SAP UI development toolkit for HTML5 (SAPUI5) (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.suite.ui.commons.BulletChart");jQuery.sap.require("sap.suite.ui.commons.library");jQuery.sap.require("sap.ui.core.Control");sap.ui.core.Control.extend("sap.suite.ui.commons.BulletChart",{metadata:{library:"sap.suite.ui.commons",properties:{"size":{type:"sap.suite.ui.commons.InfoTileSize",group:"Misc",defaultValue:sap.suite.ui.commons.InfoTileSize.Auto},"mode":{type:"sap.suite.ui.commons.BulletChartMode",group:"Misc",defaultValue:sap.suite.ui.commons.BulletChartMode.Actual},"scale":{type:"string",group:"Misc",defaultValue:null},"forecastValue":{type:"float",group:"Misc",defaultValue:null},"targetValue":{type:"float",group:"Misc",defaultValue:null},"minValue":{type:"float",group:"Misc",defaultValue:null},"maxValue":{type:"float",group:"Misc",defaultValue:null},"showActualValue":{type:"boolean",group:"Misc",defaultValue:true},"showDeltaValue":{type:"boolean",group:"Misc",defaultValue:false},"showTargetValue":{type:"boolean",group:"Misc",defaultValue:true},"showValueMarker":{type:"boolean",group:"Misc",defaultValue:false},"actualValueLabel":{type:"string",group:"Misc",defaultValue:null},"deltaValueLabel":{type:"string",group:"Misc",defaultValue:null},"targetValueLabel":{type:"string",group:"Misc",defaultValue:null},"width":{type:"string",group:"Misc",defaultValue:null},"scaleColor":{type:"sap.suite.ui.commons.CommonBackground",group:"Misc",defaultValue:sap.suite.ui.commons.CommonBackground.MediumLight}},aggregations:{"actual":{type:"sap.suite.ui.commons.BulletChartData",multiple:false},"thresholds":{type:"sap.suite.ui.commons.BulletChartData",multiple:true,singularName:"threshold"}},events:{"press":{}}}});sap.suite.ui.commons.BulletChart.M_EVENTS={'press':'press'};
sap.suite.ui.commons.BulletChart.prototype.init=function(){this._oRb=sap.ui.getCore().getLibraryResourceBundle("sap.suite.ui.commons");this.setTooltip("{AltText}");};
sap.suite.ui.commons.BulletChart.prototype._calculateChartData=function(){var s=98;var d=this.getThresholds();var t=[];var T=this.getTargetValue();var f=this.getForecastValue();var a=this.getActual()&&this.getActual().getValue()?this.getActual().getValue():0;var v=[];var l=0;var h=0;if(this.getActual()&&this.getActual()._isValueSet){v.push(a);}if(this._isForecastValueSet){v.push(f);}if(this._isTargetValueSet){v.push(T);}if(this._isMinValueSet){v.push(this.getMinValue());}if(this._isMaxValueSet){v.push(this.getMaxValue());}for(var i=0;i<d.length;i++){v.push(d[i].getValue());}var b=0;if(v.length>0){l=h=v[0];for(var j=0;j<v.length;j++){if(v[j]<l){l=v[j];}if(v[j]>h){h=v[j];}}h=(h<0&&h<3*(l-h))?0:h;l=(l>0&&l>3*(h-l))?0:l;b=h-l;for(var i=0;i<d.length;i++){t[i]={color:d[i].getColor(),valuePct:(!d[i]._isValueSet||b==0)?0:((d[i].getValue()-l)*s/b).toFixed(2)};}}return{actualValuePct:(!this.getActual()||!this.getActual()._isValueSet||b==0)?0:(.05+(a-l)*s/b).toFixed(2),targetValuePct:(!this._isTargetValueSet||b==0)?0:((T-l)*s/b).toFixed(2),forecastValuePct:(!this._isForecastValueSet||b==0)?0:((f-l)*s/b).toFixed(2),thresholdsPct:t,fScaleWidthPct:s};};
sap.suite.ui.commons.BulletChart.prototype._digitsAfterDecimalPoint=function(v){var a=(""+v).match(/[.,](\d+)/g);return(a)?(""+a).length-1:0;};
sap.suite.ui.commons.BulletChart.prototype._calculateDeltaValue=function(){if(!this.getActual()._isValueSet||!this._isTargetValueSet){return 0;}else{var a=this.getActual().getValue();var t=this.getTargetValue();return Math.abs(a-t).toFixed(Math.max(this._digitsAfterDecimalPoint(a),this._digitsAfterDecimalPoint(t)));}};
sap.suite.ui.commons.BulletChart.prototype.setMinValue=function(m,s){this._isMinValueSet=this._fnIsNumber(m);return this.setProperty("minValue",this._isMinValueSet?m:NaN,s);};
sap.suite.ui.commons.BulletChart.prototype.setMaxValue=function(m,s){this._isMaxValueSet=this._fnIsNumber(m);return this.setProperty("maxValue",this._isMaxValueSet?m:NaN,s);};
sap.suite.ui.commons.BulletChart.prototype.setTargetValue=function(t,s){this._isTargetValueSet=this._fnIsNumber(t);return this.setProperty("targetValue",this._isTargetValueSet?t:NaN,s);};
sap.suite.ui.commons.BulletChart.prototype.setForecastValue=function(f,s){this._isForecastValueSet=this._fnIsNumber(f);return this.setProperty("forecastValue",this._isForecastValueSet?f:NaN,s);};
sap.suite.ui.commons.BulletChart.prototype.ontap=function(e){if(sap.ui.Device.browser.internet_explorer){this.$().focus();}this.firePress();};
sap.suite.ui.commons.BulletChart.prototype.onkeydown=function(e){if(e.which==jQuery.sap.KeyCodes.SPACE){e.preventDefault();}};
sap.suite.ui.commons.BulletChart.prototype.onkeyup=function(e){if(e.which==jQuery.sap.KeyCodes.ENTER||e.which==jQuery.sap.KeyCodes.SPACE){this.firePress();e.preventDefault();}};
sap.suite.ui.commons.BulletChart.prototype._fnIsNumber=function(n){return typeof n=='number'&&!isNaN(n)&&isFinite(n);};
sap.suite.ui.commons.BulletChart.prototype.attachEvent=function(e,d,f,l){sap.ui.core.Control.prototype.attachEvent.call(this,e,d,f,l);if(this.hasListeners("press")){this.$().attr("tabindex",0).addClass("sapSuiteUiCommonsPointer");}return this;};
sap.suite.ui.commons.BulletChart.prototype.detachEvent=function(e,f,l){sap.ui.core.Control.prototype.detachEvent.call(this,e,f,l);if(!this.hasListeners("press")){this.$().removeAttr("tabindex").removeClass("sapSuiteUiCommonsPointer");}return this;};
sap.suite.ui.commons.BulletChart.prototype.onAfterRendering=function(){if(this._sBarResizeHandlerId){sap.ui.core.ResizeHandler.deregister(this._sBarResizeHandlerId);}var h=jQuery.sap.domById(this.getId()+"-chart-bar");this._sBarResizeHandlerId=sap.ui.core.ResizeHandler.register(h,jQuery.proxy(this._adjustLabelsPos,this));this._adjustLabelsPos();if(this.getShowValueMarker()){this._adjustValueToMarker();}};
sap.suite.ui.commons.BulletChart.prototype.exit=function(){sap.ui.core.ResizeHandler.deregister(this._sBarResizeHandlerId);};
sap.suite.ui.commons.BulletChart.prototype._adjustLabelsPos=function(){var r=sap.ui.getCore().getConfiguration().getRTL();var t=jQuery.sap.byId(this.getId()+"-bc-target-bar-value");var c=jQuery.sap.byId(this.getId()+"-chart-bar");var f=c.width();if(f){var T=0;if(t&&t.offset()){T=t.offset().left-c.offset().left;if(r){T=f-T;}this._adjustLabelPos(jQuery.sap.byId(this.getId()+"-bc-target-value"),f,T,r);}var v=jQuery.sap.byId(this.getId()+"-bc-bar-value-marker");if(v&&v.offset()){var a=v.offset().left-c.offset().left;if(r){a=f-a;}if((sap.suite.ui.commons.BulletChartMode.Delta==this.getMode())){a=(a+T)/2;}this._adjustLabelPos(jQuery.sap.byId(this.getId()+"-bc-item-value"),f,a,r);}}};
sap.suite.ui.commons.BulletChart.prototype._adjustLabelPos=function(l,f,o,r){var O=r?"right":"left";var L=l.width();if(L>f){l.css("width",""+f+"px");l.css(O,"0");}else{var a=o-.5*L;if(a<0){a=0;}if(a+L>f){a=f-L;}l.css(O,a);l.css("width",""+(parseInt(L)+1)+"px");}};
sap.suite.ui.commons.BulletChart.prototype.getLocalizedColorMeaning=function(c){return this._oRb.getText(("SEMANTIC_COLOR_"+c).toUpperCase());};
sap.suite.ui.commons.BulletChart.prototype.getAltText=function(){var I=this.getActual()&&this.getActual()._isValueSet;var s=this.getScale();var t=this.getTargetValueLabel();var m=!this.getActual()||!this.getActual().getColor()?"":this.getLocalizedColorMeaning(this.getActual().getColor());var a="";if("Delta"==this.getMode()){if(this._isTargetValueSet&&I){var d=this.getDeltaValueLabel();var D=(d)?d:""+this._calculateDeltaValue();a+=this._oRb.getText("BULLETCHART_DELTA_TOOLTIP",[D+s,m]);}}else{if(I){var A=this.getActualValueLabel();var b=(A)?A:""+this.getActual().getValue();a+=this._oRb.getText("BULLETCHART_ACTUAL_TOOLTIP",[b+s,m]);}if(this._isForecastValueSet){a+=(this._isForecastValueSet)?"\n"+this._oRb.getText("BULLETCHART_FORECAST_TOOLTIP",[this.getForecastValue()+s,m]):"";}}if(this._isTargetValueSet){var T=(t)?t:""+this.getTargetValue();a+="\n"+this._oRb.getText("BULLETCHART_TARGET_TOOLTIP",[T+s]);}var c=this.getThresholds().sort(function(f,S){return f.getValue()-S.getValue();});for(var i=0;i<c.length;i++){var o=c[i];a+="\n"+this._oRb.getText("BULLETCHART_THRESHOLD_TOOLTIP",[o.getValue()+this.getScale(),this.getLocalizedColorMeaning(o.getColor())]);}return a;};
sap.suite.ui.commons.BulletChart.prototype.getTooltip_AsString=function(){var t=this.getTooltip();var T=this.getAltText();if(typeof t==="string"||t instanceof String){T=t.split("{AltText}").join(T).split("((AltText))").join(T);return T;}return t?t:"";};
sap.suite.ui.commons.BulletChart.prototype._adjustValueToMarker=function(){var v=jQuery.sap.byId(this.getId()+"-bc-bar-value");var m=jQuery.sap.byId(this.getId()+"-bc-bar-value-marker");if(v.offset()&&m.offset()){var V=v.width();var f=v.offset().left;var M=m.width();var a=m.offset().left;if(sap.ui.getCore().getConfiguration().getRTL()){if(a<f){m.css("right","");m.offset({left:f});}if(a+M>f+V){m.css("right","");m.offset({left:f+V-M});}}else{if(a<f){m.offset({left:f});}if(a+M>f+V){v.width(a+M-f);}}}};
sap.suite.ui.commons.BulletChart.prototype.clone=function(i,l,o){var c=sap.ui.core.Control.prototype.clone.apply(this,arguments);c._isMinValueSet=this._isMinValueSet;c._isMaxValueSet=this._isMaxValueSet;c._isForecastValueSet=this._isForecastValueSet;c._isTargetValueSet=this._isTargetValueSet;return c;};
