/*!
 * SAP UI development toolkit for HTML5 (SAPUI5) (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.suite.ui.commons.ColumnMicroChart");jQuery.sap.require("sap.suite.ui.commons.library");jQuery.sap.require("sap.ui.core.Control");sap.ui.core.Control.extend("sap.suite.ui.commons.ColumnMicroChart",{metadata:{library:"sap.suite.ui.commons",properties:{"size":{type:"sap.suite.ui.commons.InfoTileSize",group:"Misc",defaultValue:sap.suite.ui.commons.InfoTileSize.Auto},"width":{type:"sap.ui.core.CSSSize",group:"Misc",defaultValue:null},"height":{type:"sap.ui.core.CSSSize",group:"Misc",defaultValue:null}},aggregations:{"columns":{type:"sap.suite.ui.commons.ColumnData",multiple:true,singularName:"column"},"leftTopLabel":{type:"sap.suite.ui.commons.ColumnMicroChartLabel",multiple:false},"rightTopLabel":{type:"sap.suite.ui.commons.ColumnMicroChartLabel",multiple:false},"leftBottomLabel":{type:"sap.suite.ui.commons.ColumnMicroChartLabel",multiple:false},"rightBottomLabel":{type:"sap.suite.ui.commons.ColumnMicroChartLabel",multiple:false}},events:{"press":{}}}});sap.suite.ui.commons.ColumnMicroChart.M_EVENTS={'press':'press'};
sap.suite.ui.commons.ColumnMicroChart.prototype.init=function(){this._oRb=sap.ui.getCore().getLibraryResourceBundle("sap.suite.ui.commons");this.setTooltip("{AltText}");};
sap.suite.ui.commons.ColumnMicroChart.prototype.onAfterRendering=function(){if(this._sChartResizeHandlerId){sap.ui.core.ResizeHandler.deregister(this._sChartResizeHandlerId);}this._sChartResizeHandlerId=sap.ui.core.ResizeHandler.register(jQuery.sap.domById(this.getId()),jQuery.proxy(this._calcColumns,this));this._fChartWidth=undefined;this._fChartHeight=undefined;this._aBars=[];var c=this.getColumns().length;for(var i=0;i<c;i++){this._aBars.push({});}this._calcColumns();};
sap.suite.ui.commons.ColumnMicroChart.prototype.exit=function(){sap.ui.core.ResizeHandler.deregister(this._sChartResizeHandlerId);};
sap.suite.ui.commons.ColumnMicroChart.prototype._calcColumns=function(){var c=this.getColumns().length;if(c){var C=parseFloat(this.$().css("width"));if(C!=this._fChartWidth){this._fChartWidth=C;var a=0;var b;if(c>1){b=jQuery.sap.byId(this.getId()+"-bar-1");var r=sap.ui.getCore().getConfiguration().getRTL();a=parseInt(b.css("margin-"+(r?"right":"left")));}else{b=jQuery.sap.byId(this.getId()+"-bar-0");}var d=parseInt(b.css("min-width"));this._calcColumnsWidth(a,d,C,this._aBars);}var f=parseFloat(this.$().css("height"));if(f!=this._fChartHeight){this._fChartHeight=f;this._calcColumnsHeight(f,this._aBars);}for(var i=0;i<c;i++){jQuery.sap.byId(this.getId()+"-bar-"+i).css(this._aBars[i]);}if(this._aBars.overflow){jQuery.sap.log.warning(this.toString()+" Chart overflow","Some columns were not rendered");}}};
sap.suite.ui.commons.ColumnMicroChart.prototype._calcColumnsWidth=function(c,C,f,b){var a=this.getColumns().length;var v=Math.floor((f+c)/(C+c));var d=Math.floor((f+c)/Math.min(v,a))-c;var s=d+"px";for(var i=0;i<a;i++){if(i<v){b[i].width=s;b[i].display="inline-block";}else{b[i].display="none";}}b.overflow=v!=a;};
sap.suite.ui.commons.ColumnMicroChart.prototype._calcColumnsHeight=function(c,b){var C=this.getColumns().length;var m,M;m=M=0;for(var i=0;i<C;i++){var o=this.getColumns()[i];if(m<o.getValue()){m=o.getValue();}else if(M>o.getValue()){M=o.getValue();}}var d=m-M;var O=d/c;var D,t;D=t=0;for(i=0;i<C;i++){var v=this.getColumns()[i].getValue();if(Math.abs(v)<O){if(v>=0){if(v==m){t=O-v;}}else{if(v==M){D=O+v;}}}}if(t){m+=t;M-=t;}if(D){m-=D;M+=D;}var n=0-O;for(i=0;i<C;i++){var v=this.getColumns()[i].getValue();var f=v;if(v>=0){f=Math.max(f+t-D,O);}else{f=Math.min(f+t-D,n);}b[i].value=f;}function a(v){return(v/d*100).toFixed(2)+"%";};var z=a(m);for(i=0;i<C;i++){var v=b[i].value;b[i].top=(v<0)?z:a(m-v);b[i].height=a(Math.abs(v));}};
sap.suite.ui.commons.ColumnMicroChart.prototype.attachEvent=function(e,d,f,l){sap.ui.core.Control.prototype.attachEvent.call(this,e,d,f,l);if(this.hasListeners("press")){this.$().attr("tabindex",0).addClass("sapSuiteUiCommonsPointer");}return this;};
sap.suite.ui.commons.ColumnMicroChart.prototype.detachEvent=function(e,f,l){sap.ui.core.Control.prototype.detachEvent.call(this,e,f,l);if(!this.hasListeners("press")){this.$().removeAttr("tabindex").removeClass("sapSuiteUiCommonsPointer");}return this;};
sap.suite.ui.commons.ColumnMicroChart.prototype.getLocalizedColorMeaning=function(c){if(c){return this._oRb.getText(("SEMANTIC_COLOR_"+c).toUpperCase());}};
sap.suite.ui.commons.ColumnMicroChart.prototype.getAltText=function(){var a="";var I=true;var l=this.getLeftTopLabel();var r=this.getRightTopLabel();var L=this.getLeftBottomLabel();var R=this.getRightBottomLabel();var c;var s=l&&l.getLabel();if(l&&l.getLabel()||L&&L.getLabel()){c=l?l.getColor():L?L.getColor():"";a+=(I?"":"\n")+this._oRb.getText(("MICRO_AREA_CHART_START"))+": "+(L?L.getLabel()+" ":"")+(l?l.getLabel()+" ":"")+this.getLocalizedColorMeaning(c);I=false;}if(r&&r.getLabel()||R&&R.getLabel()){c=r?r.getColor():R?R.getColor():"";a+=(I?"":"\n")+this._oRb.getText(("MICRO_AREA_CHART_END"))+": "+(R?R.getLabel()+" ":"")+(r?r.getLabel()+" ":"")+this.getLocalizedColorMeaning(c);I=false;}var C=this.getColumns();for(var i=0;i<C.length;i++){var b=C[i];var m=this.getLocalizedColorMeaning(b.getColor());a+=((!I||i!=0)?"\n":"")+b.getLabel()+" "+b.getValue()+" "+m;}return a;};
sap.suite.ui.commons.ColumnMicroChart.prototype.getTooltip_AsString=function(){var t=this.getTooltip();var T=this.getAltText();if(typeof t==="string"||t instanceof String){T=t.split("{AltText}").join(T).split("((AltText))").join(T);return T;}return t?t:"";};
sap.suite.ui.commons.ColumnMicroChart.prototype.ontap=function(e){if(!this.fireBarPress(e)){if(sap.ui.Device.browser.internet_explorer){this.$().focus();}this.firePress();}};
sap.suite.ui.commons.ColumnMicroChart.prototype.onkeydown=function(e){switch(e.keyCode){case jQuery.sap.KeyCodes.SPACE:e.preventDefault();break;case jQuery.sap.KeyCodes.ARROW_LEFT:case jQuery.sap.KeyCodes.ARROW_UP:var f=this.$().find(":focusable");var t=f.index(e.target);if(f.length>0){f.eq(t-1).get(0).focus();e.preventDefault();e.stopPropagation();}break;case jQuery.sap.KeyCodes.ARROW_DOWN:case jQuery.sap.KeyCodes.ARROW_RIGHT:var f=this.$().find(":focusable");var t=f.index(e.target);if(f.length>0){f.eq((t+1<f.length)?t+1:0).get(0).focus();e.preventDefault();e.stopPropagation();}break;}};
sap.suite.ui.commons.ColumnMicroChart.prototype.onkeyup=function(e){if(e.which==jQuery.sap.KeyCodes.ENTER||e.which==jQuery.sap.KeyCodes.SPACE){if(!this.fireBarPress(e)){this.firePress();e.preventDefault();}}};
sap.suite.ui.commons.ColumnMicroChart.prototype.fireBarPress=function(e){var f=this.$().find(":focus").get(0);if(f){var i=this.$().find(".sapSuiteCmcBar").index(jQuery(f));var c=this.getColumns()[i];if(c){c.firePress();e.preventDefault();e.stopPropagation();return true;}}return false;};
sap.suite.ui.commons.ColumnMicroChart.prototype._getBarAltText=function(b){var B=this.getColumns()[b];var m=this.getLocalizedColorMeaning(B.getColor());return B.getLabel()+" "+B.getValue()+" "+m;};
sap.suite.ui.commons.ColumnMicroChart.prototype.setBarPressable=function(b,p){if(p){var B=this._getBarAltText(b);jQuery.sap.byId(this.getId()+"-bar-"+b).addClass("sapSuiteUiCommonsPointer").attr("tabindex",0).attr("title",B).attr("role","presentation").attr("aria-label",B);}else{jQuery.sap.byId(this.getId()+"-bar-"+b).removeAttr("tabindex").removeClass("sapSuiteUiCommonsPointer").removeAttr("title").removeAttr("role").removeAttr("aria-label");}};
sap.suite.ui.commons.ColumnMicroChart.prototype.onsaptabnext=function(e){var l=this.$().find(":focusable").last();if(l){this._bIgnoreFocusEvt=true;l.get(0).focus();}};
sap.suite.ui.commons.ColumnMicroChart.prototype.onsaptabprevious=function(e){if(e.target.id!=e.currentTarget.id){var f=this.$().find(":focusable").first();if(f){f.get(0).focus();}}};
sap.suite.ui.commons.ColumnMicroChart.prototype.onfocusin=function(e){if(this._bIgnoreFocusEvt){this._bIgnoreFocusEvt=false;return;}if(this.getId()+"-hidden"==e.target.id){this.$().focus();e.preventDefault();e.stopPropagation();}};
