/*!
 * SAP UI development toolkit for HTML5 (SAPUI5) (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.suite.ui.commons.ComparisonChart");jQuery.sap.require("sap.suite.ui.commons.library");jQuery.sap.require("sap.ui.core.Control");sap.ui.core.Control.extend("sap.suite.ui.commons.ComparisonChart",{metadata:{library:"sap.suite.ui.commons",properties:{"scale":{type:"string",group:"Misc",defaultValue:null},"size":{type:"sap.suite.ui.commons.InfoTileSize",group:"Misc",defaultValue:sap.suite.ui.commons.InfoTileSize.Auto},"view":{type:"sap.suite.ui.commons.ComparisonChartView",group:"Appearance",defaultValue:sap.suite.ui.commons.ComparisonChartView.Normal},"width":{type:"sap.ui.core.CSSSize",group:"Misc",defaultValue:null},"colorPalette":{type:"string[]",group:"Misc",defaultValue:[]},"shrinkable":{type:"boolean",group:"Misc",defaultValue:false},"height":{type:"sap.ui.core.CSSSize",group:"Appearance",defaultValue:null}},aggregations:{"data":{type:"sap.suite.ui.commons.ComparisonData",multiple:true,singularName:"data"}},events:{"press":{}}}});sap.suite.ui.commons.ComparisonChart.M_EVENTS={'press':'press'};
/*!
 * @copyright@
 */

sap.suite.ui.commons.ComparisonChart.prototype.init=function(){this._oRb=sap.ui.getCore().getLibraryResourceBundle("sap.suite.ui.commons");this.setTooltip("{AltText}");};
sap.suite.ui.commons.ComparisonChart.prototype._calculateChartData=function(){var r=[];var d=this.getData();var c=d.length;var m=0;var M=0;var t;var a;var b;var i;for(i=0;i<c;i++){var D=isNaN(d[i].getValue())?0:d[i].getValue();m=Math.max(m,D);M=Math.min(M,D);}t=m-M;a=(t==0)?0:Math.round(m*100/t);if(a==0&&m!=0){a=1;}else if(a==100&&M!=0){a=99;}b=100-a;for(i=0;i<c;i++){var I={};var D=isNaN(d[i].getValue())?0:d[i].getValue();I.value=(t==0)?0:Math.round(D*100/t);if(I.value==0&&D!=0){I.value=(D>0)?1:-1;}else if(I.value==100){I.value=a;}else if(I.value==-100){I.value=-b;}if(I.value>=0){I.negativeNoValue=b;I.positiveNoValue=a-I.value;}else{I.value=-I.value;I.negativeNoValue=b-I.value;I.positiveNoValue=a;}r.push(I);}return r;};
sap.suite.ui.commons.ComparisonChart.prototype.attachEvent=function(e,d,f,l){sap.ui.core.Control.prototype.attachEvent.call(this,e,d,f,l);if(this.hasListeners("press")){this.$().attr("tabindex",0).addClass("sapSuiteUiCommonsPointer");}return this;};
sap.suite.ui.commons.ComparisonChart.prototype.detachEvent=function(e,f,l){sap.ui.core.Control.prototype.detachEvent.call(this,e,f,l);if(!this.hasListeners("press")){this.$().removeAttr("tabindex").removeClass("sapSuiteUiCommonsPointer");}return this;};
sap.suite.ui.commons.ComparisonChart.prototype.getLocalizedColorMeaning=function(c){return this._oRb.getText(("SEMANTIC_COLOR_"+c).toUpperCase());};
sap.suite.ui.commons.ComparisonChart.prototype.getAltText=function(){var s=this.getScale();var a="";for(var i=0;i<this.getData().length;i++){var b=this.getData()[i];var m=(this.getColorPalette().length)?"":this.getLocalizedColorMeaning(b.getColor());a+=((i==0)?"":"\n")+b.getTitle()+" "+(b.getDisplayValue()?b.getDisplayValue():b.getValue())+s+" "+m;}return a;};
sap.suite.ui.commons.ComparisonChart.prototype.getTooltip_AsString=function(){var t=this.getTooltip();var T=this.getAltText();if(typeof t==="string"||t instanceof String){T=t.split("{AltText}").join(T).split("((AltText))").join(T);return T;}return t?t:"";};
sap.suite.ui.commons.ComparisonChart.prototype._adjustBars=function(){var h=parseFloat(this.$().css("height"));var b=this.getData().length;var B=this.$().find(".sapSuiteCmpChartItem");var m=parseFloat(B.css("min-height"));var M=parseFloat(B.css("max-height"));var i;if(b!=0){i=h/b;if(i>M){i=M;}else if(i<m){i=m;}B.css("height",i);if(this.getView()==="Wide"){var c=i*79/42;this.$().find(".sapSuiteCmpChartBar>div").css("height",c+"%");}else if(this.getView()==="Normal"){var c=i-19;this.$().find(".sapSuiteCmpChartBar>div").css("height",c);}var C=(h-i*b)/2;if(C>0){jQuery(B[0]).css("margin-top",C+7+"px");}}};
sap.suite.ui.commons.ComparisonChart.prototype.onAfterRendering=function(){if(this.getHeight()!=""){var t=this;sap.ui.Device.media.attachHandler(function(){t._adjustBars();});this._adjustBars();}};
sap.suite.ui.commons.ComparisonChart.prototype._getBarAltText=function(b){var s=this.getScale();var B=this.getData()[b];var m=(this.getColorPalette().length)?"":this.getLocalizedColorMeaning(B.getColor());return B.getTitle()+" "+(B.getDisplayValue()?B.getDisplayValue():B.getValue())+s+" "+m;};
sap.suite.ui.commons.ComparisonChart.prototype.onsaptabnext=function(e){var l=this.$().find(":focusable").last();if(l){this._bIgnoreFocusEvt=true;l.get(0).focus();}};
sap.suite.ui.commons.ComparisonChart.prototype.onsaptabprevious=function(e){if(e.target.id!=e.currentTarget.id){var f=this.$().find(":focusable").first();if(f){f.get(0).focus();}}};
sap.suite.ui.commons.ComparisonChart.prototype.ontap=function(e){if(!this.fireBarPress(e)){if(sap.ui.Device.browser.internet_explorer){this.$().focus();}this.firePress();}};
sap.suite.ui.commons.ComparisonChart.prototype.onkeydown=function(e){switch(e.keyCode){case jQuery.sap.KeyCodes.SPACE:e.preventDefault();break;case jQuery.sap.KeyCodes.ARROW_LEFT:case jQuery.sap.KeyCodes.ARROW_UP:var f=this.$().find(":focusable");var t=f.index(e.target);if(f.length>0){f.eq(t-1).get(0).focus();e.preventDefault();e.stopPropagation();}break;case jQuery.sap.KeyCodes.ARROW_DOWN:case jQuery.sap.KeyCodes.ARROW_RIGHT:var f=this.$().find(":focusable");var t=f.index(e.target);if(f.length>0){f.eq((t+1<f.length)?t+1:0).get(0).focus();e.preventDefault();e.stopPropagation();}break;}};
sap.suite.ui.commons.ComparisonChart.prototype.onkeyup=function(e){if(e.which==jQuery.sap.KeyCodes.ENTER||e.which==jQuery.sap.KeyCodes.SPACE){if(!this.fireBarPress(e)){this.firePress();e.preventDefault();}}};
sap.suite.ui.commons.ComparisonChart.prototype.fireBarPress=function(e){var f=this.$().find(":focus").get(0);if(f){var i=this.$().find(".sapSuiteCmpChartBar").index(jQuery(f));var c=this.getData()[i];if(c){c.firePress();e.preventDefault();e.stopPropagation();return true;}}return false;};
sap.suite.ui.commons.ComparisonChart.prototype.setBarPressable=function(b,p){if(p){var B=this._getBarAltText(b);jQuery.sap.byId(this.getId()+"-chart-item-bar-"+b).addClass("sapSuiteUiCommonsPointer").attr("tabindex",0).attr("title",B).attr("role","presentation").attr("aria-label",B);}else{jQuery.sap.byId(this.getId()+"-chart-item-bar-"+b).removeAttr("tabindex").removeClass("sapSuiteUiCommonsPointer").removeAttr("title").removeAttr("role").removeAttr("aria-label");}};
sap.suite.ui.commons.ComparisonChart.prototype.onfocusin=function(e){if(this._bIgnoreFocusEvt){this._bIgnoreFocusEvt=false;return;}if(this.getId()+"-hidden"==e.target.id){this.$().focus();e.preventDefault();e.stopPropagation();}};
