/*!
 * SAP UI development toolkit for HTML5 (SAPUI5) (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.suite.ui.commons.DeltaMicroChart");jQuery.sap.require("sap.suite.ui.commons.library");jQuery.sap.require("sap.ui.core.Control");sap.ui.core.Control.extend("sap.suite.ui.commons.DeltaMicroChart",{metadata:{library:"sap.suite.ui.commons",properties:{"value1":{type:"float",group:"Misc",defaultValue:null},"value2":{type:"float",group:"Misc",defaultValue:null},"title1":{type:"string",group:"Misc",defaultValue:null},"title2":{type:"string",group:"Misc",defaultValue:null},"displayValue1":{type:"string",group:"Misc",defaultValue:null},"displayValue2":{type:"string",group:"Misc",defaultValue:null},"deltaDisplayValue":{type:"string",group:"Misc",defaultValue:null},"color":{type:"sap.suite.ui.commons.InfoTileValueColor",group:"Misc",defaultValue:sap.suite.ui.commons.InfoTileValueColor.Neutral},"width":{type:"sap.ui.core.CSSSize",group:"Misc",defaultValue:null},"size":{type:"sap.suite.ui.commons.InfoTileSize",group:"Misc",defaultValue:sap.suite.ui.commons.InfoTileSize.Auto}},events:{"press":{}}}});sap.suite.ui.commons.DeltaMicroChart.M_EVENTS={'press':'press'};
sap.suite.ui.commons.DeltaMicroChart.prototype.init=function(){this._oRb=sap.ui.getCore().getLibraryResourceBundle("sap.suite.ui.commons");this.setTooltip("{AltText}");};
sap.suite.ui.commons.DeltaMicroChart.prototype._calcChartData=function(){var v=this.getValue1();var V=this.getValue2();var m=Math.min(v,V,0);var M=Math.max(v,V,0);var t=M-m;function c(f){return(t==0?0:Math.abs(f)/t*100).toFixed(2);};var C={};var d=v-V;C.delta={left:M==0,width:c(d),isFirstStripeUp:v<V,isMax:(v<0&&V>=0)||(v>=0&&V<0),isZero:v==0&&V==0,isEqual:d==0};C.bar1={left:V>=0,width:c(v),isSmaller:Math.abs(v)<Math.abs(V)};C.bar2={left:v>=0,width:c(V),isSmaller:Math.abs(V)<Math.abs(v)};return C;};
sap.suite.ui.commons.DeltaMicroChart.prototype.getLocalizedColorMeaning=function(c){return this._oRb.getText(("SEMANTIC_COLOR_"+c).toUpperCase());};
sap.suite.ui.commons.DeltaMicroChart.prototype._digitsAfterDecimalPoint=function(v){var a=(""+v).match(/[.,](\d+)/g);return(a)?(""+a).length-1:0;};
sap.suite.ui.commons.DeltaMicroChart.prototype.getAltText=function(){var d=this.getDisplayValue1();var D=this.getDisplayValue2();var s=this.getDeltaDisplayValue();var v=this.getValue1();var V=this.getValue2();var a=d?d:""+v;var A=D?D:""+V;var b=s?s:""+Math.abs(v-V).toFixed(Math.max(this._digitsAfterDecimalPoint(v),this._digitsAfterDecimalPoint(V)));var m=this.getLocalizedColorMeaning(this.getColor());return this.getTitle1()+" "+a+"\n"+this.getTitle2()+" "+A+"\n"+this._oRb.getText("DELTAMICROCHART_DELTA_TOOLTIP",[b,m]);};
sap.suite.ui.commons.DeltaMicroChart.prototype.getTooltip_AsString=function(){var t=this.getTooltip();var T=this.getAltText();if(typeof t==="string"||t instanceof String){T=t.split("{AltText}").join(T).split("((AltText))").join(T);return T;}return t?t:"";};
sap.suite.ui.commons.DeltaMicroChart.prototype._isCalcSupported=function(){return"11px"==jQuery.sap.byId(this.getId()+"-calc").css("max-width");};
sap.suite.ui.commons.DeltaMicroChart.prototype._isRoundingSupported=function(){return 4==jQuery.sap.byId(this.getId()+"-calc1").width();};
sap.suite.ui.commons.DeltaMicroChart.prototype.onBeforeRendering=function(){this._oChartData=this._calcChartData();};
sap.suite.ui.commons.DeltaMicroChart.prototype.onAfterRendering=function(){this._bCalc=this._isCalcSupported();this._bRounding=this._isRoundingSupported();if(!this._bCalc||!this._bRounding){if(this._sResizeHandlerId){sap.ui.core.ResizeHandler.deregister(this._sResizeHandlerId);}var c=jQuery.sap.domById(this.getId()+"-dmc-chart");this._sResizeHandlerId=sap.ui.core.ResizeHandler.register(c,jQuery.proxy(this._adjust,this));if(!this._bCalc){this._adjustCalc();}if(!this._bRounding){this._adjustRound();}}};
sap.suite.ui.commons.DeltaMicroChart.prototype._adjust=function(){if(!this._bCalc){this._adjustCalc();}if(!this._bRounding){this._adjustRound();}};
sap.suite.ui.commons.DeltaMicroChart.prototype._adjustRound=function(){var c=jQuery.sap.byId(this.getId()+"-dmc-chart").width();var d=Math.round(c*this._oChartData.delta.width/100);jQuery.sap.byId(this.getId()+"-dmc-bar-delta").width(d);if(this._oChartData.bar1.isSmaller&&!this._oChartData.delta.isMax){jQuery.sap.byId(this.getId()+"-dmc-bar1").width(c-d);}if(this._oChartData.bar2.isSmaller&&!this._oChartData.delta.isMax){jQuery.sap.byId(this.getId()+"-dmc-bar2").width(c-d);}};
sap.suite.ui.commons.DeltaMicroChart.prototype._adjustCalc=function(){var c=jQuery.sap.byId(this.getId()+"-dmc-chart").width();function a(b){b.css("max-width",c-parseInt(b.css("max-width"))+"px");};a(jQuery.sap.byId(this.getId()+"-dmc-bar1"));a(jQuery.sap.byId(this.getId()+"-dmc-bar2"));a(jQuery.sap.byId(this.getId()+"-dmc-bar-delta"));};
sap.suite.ui.commons.DeltaMicroChart.prototype.attachEvent=function(e,d,f,l){sap.ui.core.Control.prototype.attachEvent.call(this,e,d,f,l);if(this.hasListeners("press")){this.$().attr("tabindex",0).addClass("sapSuiteUiCommonsPointer");}return this;};
sap.suite.ui.commons.DeltaMicroChart.prototype.detachEvent=function(e,f,l){sap.ui.core.Control.prototype.detachEvent.call(this,e,f,l);if(!this.hasListeners("press")){this.$().removeAttr("tabindex").removeClass("sapSuiteUiCommonsPointer");}return this;};
sap.suite.ui.commons.DeltaMicroChart.prototype.ontap=function(e){if(sap.ui.Device.browser.internet_explorer){this.$().focus();}this.firePress();};
sap.suite.ui.commons.DeltaMicroChart.prototype.onkeydown=function(e){if(e.which==jQuery.sap.KeyCodes.SPACE){e.preventDefault();}};
sap.suite.ui.commons.DeltaMicroChart.prototype.onkeyup=function(e){if(e.which==jQuery.sap.KeyCodes.ENTER||e.which==jQuery.sap.KeyCodes.SPACE){this.firePress();e.preventDefault();}};
