/*!
 * SAP UI development toolkit for HTML5 (SAPUI5) (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.suite.ui.commons.ProcessFlowConnection");jQuery.sap.require("sap.suite.ui.commons.library");jQuery.sap.require("sap.ui.core.Control");sap.ui.core.Control.extend("sap.suite.ui.commons.ProcessFlowConnection",{metadata:{library:"sap.suite.ui.commons",properties:{"drawData":{type:"object[]",group:"Misc",defaultValue:null},"zoomLevel":{type:"sap.suite.ui.commons.ProcessFlowZoomLevel",group:"Misc",defaultValue:sap.suite.ui.commons.ProcessFlowZoomLevel.Two}}}});sap.suite.ui.commons.ProcessFlowConnection.prototype._oResBundle=null;
sap.suite.ui.commons.ProcessFlowConnection.prototype.init=function(){if(!this._oResBundle){this._oResBundle=sap.ui.getCore().getLibraryResourceBundle("sap.suite.ui.commons");}};
sap.suite.ui.commons.ProcessFlowConnection.prototype._traverseConnectionData=function(){var c=this.getDrawData();if(!c){return{};}var l={draw:false,state:"",display:""};var a={right:l,top:l,left:l,bottom:l,arrow:false};function s(m,b,d){var e={draw:d.draw,state:d.state,display:d.display};if(m.flowLine.indexOf(b)>=0){e.draw=true;if(m.targetNodeState===sap.suite.ui.commons.ProcessFlowNodeState.Neutral||m.targetNodeState===sap.suite.ui.commons.ProcessFlowNodeState.Positive||m.targetNodeState===sap.suite.ui.commons.ProcessFlowNodeState.Negative){e.state="Created";}else if(m.targetNodeState===sap.suite.ui.commons.ProcessFlowNodeState.Planned||m.targetNodeState===sap.suite.ui.commons.ProcessFlowNodeState.PlannedNegative){if(e.state!=="Created"){e.state="Planned";}}if(m.displayState===sap.suite.ui.commons.ProcessFlowDisplayState.Highlighted||m.displayState===sap.suite.ui.commons.ProcessFlowDisplayState.HighlightedFocused){e.display="Highlighted";}else if(m.displayState===sap.suite.ui.commons.ProcessFlowDisplayState.Regular||m.displayState===sap.suite.ui.commons.ProcessFlowDisplayState.RegularFocused){if(e.display!=="Highlighted"){e.display="Regular";}}else if(m.displayState===sap.suite.ui.commons.ProcessFlowDisplayState.Dimmed||m.displayState===sap.suite.ui.commons.ProcessFlowDisplayState.DimmedFocused){if(e.display!=="Highlighted"&&e.display!=="Regular"){e.display="Dimmed";}}}return e;}var i;for(i=0;i<c.length;i++){a.right=s(c[i],"r",a.right);a.top=s(c[i],"t",a.top);a.left=s(c[i],"l",a.left);a.bottom=s(c[i],"b",a.bottom);if(c[i].flowLine.indexOf("r")>=0){if(c[i].hasArrow){a.arrow=true;}}}return a;};
sap.suite.ui.commons.ProcessFlowConnection.prototype.addConnectionData=function(s){var t=this.getDrawData();if(!t){t=[];}t.push(s);this.setDrawData(t);return t;};
sap.suite.ui.commons.ProcessFlowConnection.prototype._getAriaText=function(){var c=this._traverseConnectionData();var a="";var w=" "+this._oResBundle.getText('PF_CONNECTION_ENDS');if(this._isHorizontalLine(c)){a=this._oResBundle.getText('PF_CONNECTION_HORIZONTAL_LINE');if(c.arrow){a+=w;}}else if(this._isVerticalLine(c)){a=this._oResBundle.getText('PF_CONNECTION_VERTICAL_LINE');if(c.arrow){a+=w;}}else{a=this._oResBundle.getText('PF_CONNECTION_BRANCH');if(c.arrow){a+=w;}}return a;};
sap.suite.ui.commons.ProcessFlowConnection.prototype._isVerticalLine=function(c){if(c.hasOwnProperty("left")&&!c.left.draw&&c.hasOwnProperty("right")&&!c.right.draw&&c.hasOwnProperty("top")&&c.top.draw&&c.hasOwnProperty("bottom")&&c.bottom.draw){return true;}else{return false;}};
sap.suite.ui.commons.ProcessFlowConnection.prototype._isHorizontalLine=function(c){if(c.hasOwnProperty("left")&&c.left.draw&&c.hasOwnProperty("right")&&c.right.draw&&c.hasOwnProperty("top")&&!c.top.draw&&c.hasOwnProperty("bottom")&&!c.bottom.draw){return true;}else{return false;}};
