/*!
 * SAP UI development toolkit for HTML5 (SAPUI5) (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.suite.ui.commons.ThingCollection");jQuery.sap.require("sap.suite.ui.commons.library");jQuery.sap.require("sap.ui.core.Control");sap.ui.core.Control.extend("sap.suite.ui.commons.ThingCollection",{metadata:{publicMethods:["shiftPrev","shiftNext","addNextContent"],library:"sap.suite.ui.commons",properties:{"width":{type:"sap.ui.core.CSSSize",group:"Misc",defaultValue:'100%'},"height":{type:"sap.ui.core.CSSSize",group:"Misc",defaultValue:'100%'},"minWidth":{type:"sap.ui.core.CSSSize",group:"Misc",defaultValue:null},"minHeight":{type:"sap.ui.core.CSSSize",group:"Misc",defaultValue:null}},aggregations:{"content":{type:"sap.ui.ux3.ThingViewer",multiple:true,singularName:"content"}}}});
sap.suite.ui.commons.ThingCollection.prototype.init=function(){this._iCenterNum=0;this._bScrollDisabled=false;var t=this;this._rb=sap.ui.getCore().getLibraryResourceBundle("sap.suite.ui.commons");this._oRemoveButton=new sap.ui.commons.Link({id:this.getId()+"-remove-button",tooltip:this._rb.getText("THINGCOLLECTION_BUTTON_REMOVE_TOOLTIP"),press:function(){t._removeCenterContent();}});this._oRemoveButton.addStyleClass("sapUiUx3OverlayCloseButton");this._initTouchEvents();};
sap.suite.ui.commons.ThingCollection.prototype.exit=function(){this._oRemoveButton.destroy();};
sap.suite.ui.commons.ThingCollection.prototype.onBeforeRendering=function(){this._oCenterControl=this.getContent()[this._iCenterNum]||null;};
sap.suite.ui.commons.ThingCollection.prototype.onAfterRendering=function(){var t=this;jQuery.sap.byId(this.getId()+"-nav-prev").bind("click",function(){t.shiftPrev();});jQuery.sap.byId(this.getId()+"-nav-next").bind("click",function(){t.shiftNext();});this._updateArrows();if(this.getContent().length<=1){this._hideRemoveButton();}jQuery.sap.byId(this._oRemoveButton.getId()).attr("role","button");jQuery.sap.byId(this._oRemoveButton.getId()).attr("aria-disabled","false");};
sap.suite.ui.commons.ThingCollection.prototype.addContent=function(c){this.addAggregation("content",c,true);this._updateArrows();this._showRemoveButton();return this;};
sap.suite.ui.commons.ThingCollection.prototype.addNextContent=function(c){this.insertAggregation("content",c,this._iCenterNum+1,true);this._updateArrows();this._showRemoveButton();return this;};
sap.suite.ui.commons.ThingCollection.prototype.shiftPrev=function(){if(this._isShiftPrevForbidden()){return;}var t=this;this._hideRemoveButton();this._bScrollDisabled=true;var c="#"+this.getId()+"-container";var p=jQuery(c+">.sapSuiteTcPrev");var C=jQuery(c+">.sapSuiteTcCenter");var n=jQuery(c+">.sapSuiteTcNext");var r=sap.ui.getCore().createRenderManager();var d=sap.ui.getCore().getConfiguration().getRTL()?"right":"left";this._iCenterNum--;var D={};D[d]="+=110%";this._renderPrevPanel(r,this.getContent()[this._iCenterNum]);C.animate(D,800);p.animate(D,800,function(){n.css(d,"-110%");t._renderNextPanel(r);r.destroy();t._bScrollDisabled=false;t._updateArrows();t._showRemoveButton();jQuery(c).focus();C.show();});p.removeClass("sapSuiteTcPrev").addClass("sapSuiteTcCenter").attr("aria-hidden","false");C.removeClass("sapSuiteTcCenter").addClass("sapSuiteTcNext").attr("aria-hidden","true");n.removeClass("sapSuiteTcNext").addClass("sapSuiteTcPrev");};
sap.suite.ui.commons.ThingCollection.prototype.shiftNext=function(){if(this._isShiftNextForbidden()){return;}var t=this;this._hideRemoveButton();this._bScrollDisabled=true;var c="#"+this.getId()+"-container";var p=jQuery(c+">.sapSuiteTcPrev");var C=jQuery(c+">.sapSuiteTcCenter");var n=jQuery(c+">.sapSuiteTcNext");var r=sap.ui.getCore().createRenderManager();var d=sap.ui.getCore().getConfiguration().getRTL()?"right":"left";this._iCenterNum++;var D={};D[d]="-=110%";this._renderNextPanel(r,this.getContent()[this._iCenterNum]);C.animate(D,800);n.animate(D,800,function(){p.css(d,"110%");t._renderPrevPanel(r);r.destroy();t._bScrollDisabled=false;t._updateArrows();t._showRemoveButton();jQuery(c).focus();C.show();});p.removeClass("sapSuiteTcPrev").addClass("sapSuiteTcNext");C.removeClass("sapSuiteTcCenter").addClass("sapSuiteTcPrev").attr("aria-hidden","true");n.removeClass("sapSuiteTcNext").addClass("sapSuiteTcCenter").attr("aria-hidden","false");};
sap.suite.ui.commons.ThingCollection.prototype.onsapprevious=function(e){this.shiftPrev();e.preventDefault();};
sap.suite.ui.commons.ThingCollection.prototype.onsapnext=function(e){this.shiftNext();e.preventDefault();};
sap.suite.ui.commons.ThingCollection.prototype._initTouchEvents=function(){if(jQuery.sap.touchEventMode!="OFF"){var t=this;this.onswipeleft=function(e){e.preventDefault();t.shiftNext();};this.onswiperight=function(e){e.preventDefault();t.shiftPrev();};}};
sap.suite.ui.commons.ThingCollection.prototype._removeCenterContent=function(){this._hideRemoveButton();this.removeAggregation("content",this.getContent()[this._iCenterNum],true);var t=this;var c=this.getContent().length;var C=jQuery("#"+this.getId()+"-container>.sapSuiteTcCenter");C.hide(600);if(t._iCenterNum>=c){t._iCenterNum=c;t.shiftPrev();}else{t._iCenterNum-=1;t.shiftNext();}};
sap.suite.ui.commons.ThingCollection.prototype._showRemoveButton=function(){if(this.getContent().length>1){jQuery.sap.byId(this.getId()+"-remove-button").show();}};
sap.suite.ui.commons.ThingCollection.prototype._hideRemoveButton=function(){jQuery.sap.byId(this.getId()+"-remove-button").hide();};
sap.suite.ui.commons.ThingCollection.prototype._updateArrows=function(){var n=jQuery.sap.byId(this.getId()+"-nav-prev");var N=jQuery.sap.byId(this.getId()+"-nav-next");var p="";var s="";if(this._isShiftPrevForbidden()){n.removeClass("sapSuiteTcNavPrevArrow");}else{n.addClass("sapSuiteTcNavPrevArrow");p=this._rb.getText("THINGCOLLECTION_BUTTON_PREVIOUS_TOOLTIP");}n.attr("title",p);if(this._isShiftNextForbidden()){N.removeClass("sapSuiteTcNavNextArrow");}else{N.addClass("sapSuiteTcNavNextArrow");s=this._rb.getText("THINGCOLLECTION_BUTTON_NEXT_TOOLTIP");}N.attr("title",s);};
sap.suite.ui.commons.ThingCollection.prototype._isShiftPrevForbidden=function(){return this._bScrollDisabled||(this._iCenterNum<=0);};
sap.suite.ui.commons.ThingCollection.prototype._isShiftNextForbidden=function(){return this._bScrollDisabled||(this._iCenterNum>=this.getContent().length-1);};
sap.suite.ui.commons.ThingCollection.prototype._renderPrevPanel=function(r,c){this._renderPanel(r,c,true);};
sap.suite.ui.commons.ThingCollection.prototype._renderNextPanel=function(r,c){this._renderPanel(r,c,false);};
sap.suite.ui.commons.ThingCollection.prototype._renderPanel=function(r,c,l){var p="#"+this.getId()+"-container>"+(l?".sapSuiteTcPrev":".sapSuiteTcNext");var P=jQuery(p);if(P.length>0){if(c){r.renderControl(c);}else{r.write("");}r.flush(P[0]);}};
