/*!
 * SAP UI development toolkit for HTML5 (SAPUI5) (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.suite.ui.commons.TileContent");jQuery.sap.require("sap.suite.ui.commons.library");jQuery.sap.require("sap.ui.core.Control");sap.ui.core.Control.extend("sap.suite.ui.commons.TileContent",{metadata:{library:"sap.suite.ui.commons",properties:{"footer":{type:"string",group:"Appearance",defaultValue:null},"size":{type:"sap.suite.ui.commons.InfoTileSize",group:"Misc",defaultValue:"Auto"},"unit":{type:"string",group:"Misc",defaultValue:null},"disabled":{type:"boolean",group:"Misc",defaultValue:false},"frameType":{type:"sap.suite.ui.commons.FrameType",group:"Appearance",defaultValue:sap.suite.ui.commons.FrameType.Auto}},aggregations:{"content":{type:"sap.ui.core.Control",multiple:false}}}});
sap.suite.ui.commons.TileContent.prototype.init=function(){this._oDelegate={onAfterRendering:function(e){e.srcControl.$().removeAttr("tabindex");}};};
sap.suite.ui.commons.TileContent.prototype._getContentType=function(){if(this.getContent()){var c=this.getContent().getMetadata().getName();if(c=="sap.suite.ui.commons.NewsContent"){return"News";}}};
sap.suite.ui.commons.TileContent.prototype.onAfterRendering=function(){var c=this.getContent();if(c){var t=jQuery(this.getDomRef());if(!t.attr("title")){var C=c.getTooltip_AsString();var T=t.find("*");T.removeAttr("title");var o=C?C:"";t.attr("title",o+"\n"+this._getFooterText());}}};
sap.suite.ui.commons.TileContent.prototype._getFooterText=function(){var f=this.getFooter();var u=this.getUnit();return u?(sap.ui.getCore().getConfiguration().getRTL()?((f?f+" ,":"")+u):(u+(f?", "+f:""))):f;};
sap.suite.ui.commons.TileContent.prototype.onBeforeRendering=function(){if(this.getContent()){if(this.getDisabled()){this.getContent().addDelegate(this._oDelegate);}else{this.getContent().removeDelegate(this._oDelegate);}}};
sap.suite.ui.commons.TileContent.prototype.setContent=function(o,s){if(this.getContent()){this.getContent().removeDelegate(this._oDelegate);}this.setAggregation("content",o,s);};
sap.suite.ui.commons.TileContent.prototype.getAltText=function(){var a="";var i=true;var c=this.getContent();if(c){if(c.getAltText){a+=c.getAltText();i=false;}else if(c.getTooltip_AsString()){a+=c.getTooltip_AsString();i=false;}}if(this.getUnit()){a+=(i?"":"\n")+this.getUnit();i=false;}if(this.getFooter()){a+=(i?"":"\n")+this.getFooter();}return a;};
