/*!
 * SAP UI development toolkit for HTML5 (SAPUI5) (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.suite.ui.commons.ColumnMicroChart");jQuery.sap.require("sap.suite.ui.commons.library");jQuery.sap.require("sap.ui.core.Control");sap.ui.core.Control.extend("sap.suite.ui.commons.ColumnMicroChart",{metadata:{library:"sap.suite.ui.commons",properties:{"size":{type:"sap.suite.ui.commons.InfoTileSize",group:"Misc",defaultValue:sap.suite.ui.commons.InfoTileSize.Auto},"width":{type:"sap.ui.core.CSSSize",group:"Misc",defaultValue:null},"height":{type:"sap.ui.core.CSSSize",group:"Misc",defaultValue:null}},aggregations:{"columns":{type:"sap.suite.ui.commons.ColumnData",multiple:true,singularName:"column"}},events:{"press":{}}}});sap.suite.ui.commons.ColumnMicroChart.M_EVENTS={'press':'press'};
sap.suite.ui.commons.ColumnMicroChart.prototype.init=function(){this._oRb=sap.ui.getCore().getLibraryResourceBundle("sap.suite.ui.commons")};
sap.suite.ui.commons.ColumnMicroChart.prototype.onAfterRendering=function(){if(this._sChartResizeHandlerId){sap.ui.core.ResizeHandler.deregister(this._sChartResizeHandlerId)}this._sChartResizeHandlerId=sap.ui.core.ResizeHandler.register(jQuery.sap.domById(this.getId()),jQuery.proxy(this._calcColumns,this));this._fChartWidth=undefined;this._fChartHeight=undefined;this._aBars=[];var c=this.getColumns().length;for(var i=0;i<c;i++){this._aBars.push({})}this._calcColumns()};
sap.suite.ui.commons.ColumnMicroChart.prototype.exit=function(){sap.ui.core.ResizeHandler.deregister(this._sChartResizeHandlerId)};
sap.suite.ui.commons.ColumnMicroChart.prototype._calcColumns=function(){var c=this.getColumns().length;if(c){var C=parseFloat(this.$().css("width"));if(C!=this._fChartWidth){this._fChartWidth=C;var a=0;var b;if(c>1){b=jQuery.sap.byId(this.getId()+"-bar-1");var r=sap.ui.getCore().getConfiguration().getRTL();a=parseInt(b.css("margin-"+(r?"right":"left")))}else{b=jQuery.sap.byId(this.getId()+"-bar-0")}var d=parseInt(b.css("min-width"));this._calcColumnsWidth(a,d,C,this._aBars)}var f=parseFloat(this.$().css("height"));if(f!=this._fChartHeight){this._fChartHeight=f;this._calcColumnsHeight(f,this._aBars)}for(var i=0;i<c;i++){jQuery.sap.byId(this.getId()+"-bar-"+i).css(this._aBars[i])}if(this._aBars.overflow){jQuery.sap.log.warning(this.toString()+" Chart overflow","Some columns were not rendered")}}};
sap.suite.ui.commons.ColumnMicroChart.prototype._calcColumnsWidth=function(c,C,f,b){var a=this.getColumns().length;var v=Math.floor((f+c)/(C+c));var d=Math.floor((f+c)/Math.min(v,a))-c;var s=d+"px";for(var i=0;i<a;i++){if(i<v){b[i].width=s;b[i].display="inline-block"}else{b[i].display="none"}}b.overflow=v!=a};
sap.suite.ui.commons.ColumnMicroChart.prototype._calcColumnsHeight=function(c,b){var C=this.getColumns().length;var m,M;m=M=0;for(var i=0;i<C;i++){var o=this.getColumns()[i];if(m<o.getValue()){m=o.getValue()}else if(M>o.getValue()){M=o.getValue()}}var d=m-M;var O=d/c;var D,t;D=t=0;for(i=0;i<C;i++){var v=this.getColumns()[i].getValue();if(Math.abs(v)<O){if(v>=0){if(v==m){t=O-v}}else{if(v==M){D=O+v}}}}if(t){m+=t;M-=t}if(D){m-=D;M+=D}var n=0-O;for(i=0;i<C;i++){var v=this.getColumns()[i].getValue();var f=v;if(v>=0){f=Math.max(f+t-D,O)}else{f=Math.min(f+t-D,n)}b[i].value=f}function a(v){return(v/d*100).toFixed(2)+"%"};var z=a(m);for(i=0;i<C;i++){var v=b[i].value;b[i].top=(v<0)?z:a(m-v);b[i].height=a(Math.abs(v))}};
sap.suite.ui.commons.ColumnMicroChart.prototype.attachEvent=function(e,d,f,l){sap.ui.core.Control.prototype.attachEvent.call(this,e,d,f,l);if(this.hasListeners("press")){this.$().attr("tabindex",0).attr("role","button").addClass("sapSuiteUiCommonsPointer")}return this};
sap.suite.ui.commons.ColumnMicroChart.prototype.detachEvent=function(e,f,l){sap.ui.core.Control.prototype.detachEvent.call(this,e,f,l);if(!this.hasListeners("press")){this.$().removeAttr("tabindex").attr("role","img").removeClass("sapSuiteUiCommonsPointer")}return this};
sap.suite.ui.commons.ColumnMicroChart.prototype.ontap=function(e){if(sap.ui.Device.browser.internet_explorer){this.$().focus()}this.firePress()};
sap.suite.ui.commons.ColumnMicroChart.prototype.onkeydown=function(e){if(e.which==jQuery.sap.KeyCodes.ENTER||e.which==jQuery.sap.KeyCodes.SPACE){this.firePress();e.preventDefault()}};
sap.suite.ui.commons.ColumnMicroChart.prototype.getLocalizedColorMeaning=function(c){return this._oRb.getText(("SEMANTIC_COLOR_"+c).toUpperCase())};
sap.suite.ui.commons.ColumnMicroChart.prototype.getAltText=function(){var a="";var c=this.getColumns();for(var i=0;i<c.length;i++){var b=c[i];var m=this.getLocalizedColorMeaning(b.getColor());a+=((i==0)?"":"\n")+b.getLabel()+" "+b.getValue()+" "+m}return a};
sap.suite.ui.commons.ColumnMicroChart.prototype.getTooltip_AsString=function(){var t=this.getTooltip();var T=this.getAltText();if(typeof t==="string"||t instanceof String){if(t.indexOf("{AltText}")!=-1){T=t.split("{AltText}").join(T)}else{T=t}}return T};
