/*!
 * SAP UI development toolkit for HTML5 (SAPUI5) (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.suite.ui.commons.HeaderContainer");jQuery.sap.require("sap.suite.ui.commons.library");jQuery.sap.require("sap.ui.core.Control");sap.ui.core.Control.extend("sap.suite.ui.commons.HeaderContainer",{metadata:{interfaces:["sap.m.ObjectHeaderContainer"],library:"sap.suite.ui.commons",properties:{"scrollStep":{type:"int",group:"Misc",defaultValue:300},"scrollTime":{type:"int",group:"Misc",defaultValue:500}},aggregations:{"scrollContainer":{type:"sap.ui.core.Control",multiple:false,visibility:"hidden"},"items":{type:"sap.ui.core.Control",multiple:true,singularName:"item"},"buttonPrev":{type:"sap.ui.core.Control",multiple:false,visibility:"hidden"},"buttonNext":{type:"sap.ui.core.Control",multiple:false,visibility:"hidden"}}}});jQuery.sap.require("sap.ui.core.IconPool");jQuery.sap.require("sap.ui.core.Icon");jQuery.sap.require("sap.ui.core.delegate.ItemNavigation");
sap.suite.ui.commons.HeaderContainer.prototype.init=function(){this._bRtl=sap.ui.getCore().getConfiguration().getRTL();this._rb=sap.ui.getCore().getLibraryResourceBundle("sap.suite.ui.commons");this._oScrollCntr=new sap.m.ScrollContainer(this.getId()+"-scrl-cntnr",{width:"100%",horizontal:!jQuery.device.is.desktop});this.setAggregation("scrollContainer",this._oScrollCntr);var t=this;if(jQuery.device.is.desktop){this._oArrowPrev=new sap.m.Button({id:this.getId()+"-scrl-prev-button",icon:"sap-icon://navigation-left-arrow",type:sap.m.ButtonType.Transparent,tooltip:this._rb.getText("HEADERCONTAINER_BUTTON_PREV_SECTION"),press:function(e){t._scroll(-t.getScrollStep(),t.getScrollTime())}});this._oArrowPrev.addStyleClass("sapSuiteHdrCntrBtn").addStyleClass("sapSuiteHdrCntrLeft");this.setAggregation("buttonPrev",this._oArrowPrev);this._oArrowNext=new sap.m.Button({id:this.getId()+"-scrl-next-button",icon:"sap-icon://navigation-right-arrow",type:sap.m.ButtonType.Transparent,tooltip:this._rb.getText("HEADERCONTAINER_BUTTON_NEXT_SECTION"),press:function(e){t._scroll(t.getScrollStep(),t.getScrollTime())}});this._oArrowNext.addStyleClass("sapSuiteHdrCntrBtn").addStyleClass("sapSuiteHdrCntrRight");this.setAggregation("buttonNext",this._oArrowNext);this._oScrollCntr.addDelegate({onAfterRendering:function(o){if(jQuery.device.is.desktop){var f=jQuery.sap.domById(t.getId()+"-scrl-cntnr-scroll");var F=jQuery.sap.byId(t.getId()+"-scrl-cntnr-scroll");var d=F.find("[tabindex=0]");if(!t._oItemNavigation){t._oItemNavigation=new sap.ui.core.delegate.ItemNavigation();t.addDelegate(t._oItemNavigation);t._oItemNavigation.attachEvent(sap.ui.core.delegate.ItemNavigation.Events.BorderReached,t._handleBorderReached,t);t._oItemNavigation.attachEvent(sap.ui.core.delegate.ItemNavigation.Events.AfterFocus,t._handleBorderReached,t)}t._oItemNavigation.setRootDomRef(f);t._oItemNavigation.setItemDomRefs(d);t._oItemNavigation.setCycling(false)}},onBeforeRendering:function(o){if(jQuery.device.is.desktop){jQuery.sap.require("sap.ui.core.delegate.ScrollEnablement");t._oScrollCntr._oScroller=new sap.ui.core.delegate.ScrollEnablement(t._oScrollCntr,t._oScrollCntr.getId()+"-scroll",{horizontal:true,vertical:false,zynga:true,preventDefault:false,nonTouchScrolling:"scrollbar"})}}})}};
sap.suite.ui.commons.HeaderContainer.prototype._scroll=function(d,D){var o=jQuery.sap.domById(this.getId()+"-scrl-cntnr");var s=o.scrollLeft;if(!sap.ui.Device.browser.internet_explorer&&this._bRtl){d=-d}var S=s+d;this._oScrollCntr.scrollTo(S,0,D)};
sap.suite.ui.commons.HeaderContainer.prototype._checkOverflow=function(){var b=jQuery.sap.domById(this.getId()+"-scrl-cntnr");var s=false;if(b){if(b.scrollWidth>b.clientWidth){s=true}}this._lastScrolling=s;if(b){var S=b.scrollLeft;var a=false;var c=false;var r=b.scrollWidth;var d=b.clientWidth;if(Math.abs(r-d)==1){r=d}if(!this._bRtl){if(S>0){a=true}if((r>d)&&(S+d<r)){c=true}}else{var l=jQuery(b);if(l.scrollLeftRTL()>0){c=true}if(l.scrollRightRTL()>0){a=true}}var o=jQuery.sap.byId(this.getId()+"-scroll-area");if(!a){jQuery.sap.byId(this._oArrowPrev.getId()).hide();o.css(this._bRtl?"padding-right":"padding-left","0rem")}else{jQuery.sap.byId(this._oArrowPrev.getId()).show();o.css(this._bRtl?"padding-right":"padding-left","2rem")}if(!c){jQuery.sap.byId(this._oArrowNext.getId()).hide();o.css(this._bRtl?"padding-left":"padding-right","0rem")}else{jQuery.sap.byId(this._oArrowNext.getId()).show();o.css(this._bRtl?"padding-left":"padding-right","2rem")}}};
sap.suite.ui.commons.HeaderContainer.prototype._handleBorderReached=function(o){var i=o.getParameter("index");if(i==0){this._scroll(-this.getScrollStep(),this.getScrollTime())}else if(i==this.getItems().length-1){this._scroll(this.getScrollStep(),this.getScrollTime())}};
sap.suite.ui.commons.HeaderContainer.prototype.addItem=function(i,s){return this._oScrollCntr.addContent(i.addStyleClass("sapSuiteHrdrCntrInner"),s)};
sap.suite.ui.commons.HeaderContainer.prototype.insertItem=function(i,I,s){return this._oScrollCntr.insertContent(i.addStyleClass("sapSuiteHrdrCntrInner"),I,s)};
sap.suite.ui.commons.HeaderContainer.prototype._callMethodInManagedObject=function(f,a){var b=Array.prototype.slice.call(arguments);if(a==="items"){b[1]="content";return this._oScrollCntr[f].apply(this._oScrollCntr,b.slice(1))}else{return sap.ui.base.ManagedObject.prototype[f].apply(this,b.slice(1))}};
sap.suite.ui.commons.HeaderContainer.prototype.onBeforeRendering=function(){if(jQuery.device.is.desktop){sap.ui.getCore().attachIntervalTimer(this._checkOverflow,this)}if(jQuery.device.is.desktop){this.$().unbind("click",this.handleSwipe)}};
sap.suite.ui.commons.HeaderContainer.prototype.onAfterRendering=function(){jQuery.sap.byId(this.getId()+"-scrl-next-button").attr("tabindex","-1");jQuery.sap.byId(this.getId()+"-scrl-prev-button").attr("tabindex","-1");if(jQuery.device.is.desktop){this.$().bind("swipe",jQuery.proxy(this.handleSwipe,this))}};
sap.suite.ui.commons.HeaderContainer.prototype.handleSwipe=function(e){e.preventDefault();e.stopPropagation();this._isDragEvent=true};
sap.suite.ui.commons.HeaderContainer.prototype.exit=function(){if(this._oItemNavigation){this.removeDelegate(this._oItemNavigation);this._oItemNavigation.destroy()}};
sap.suite.ui.commons.HeaderContainer.prototype.onclick=function(e){if(this._isDragEvent){e.preventDefault();e.stopPropagation();this._isDragEvent=false}};
sap.suite.ui.commons.HeaderContainer.prototype.validateAggregation=function(a,o,m){return this._callMethodInManagedObject("validateAggregation",a,o,m)};
sap.suite.ui.commons.HeaderContainer.prototype.getAggregation=function(a,o,s){return this._callMethodInManagedObject("getAggregation",a,o,s)};
sap.suite.ui.commons.HeaderContainer.prototype.setAggregation=function(a,o,s){this._callMethodInManagedObject("setAggregation",a,o,s);return this};
sap.suite.ui.commons.HeaderContainer.prototype.indexOfAggregation=function(a,o){return this._callMethodInManagedObject("indexOfAggregation",a,o)};
sap.suite.ui.commons.HeaderContainer.prototype.insertAggregation=function(a,o,i,s){this._callMethodInManagedObject("insertAggregation",a,o,i,s);return this};
sap.suite.ui.commons.HeaderContainer.prototype.addAggregation=function(a,o,s){this._callMethodInManagedObject("addAggregation",a,o,s);return this};
sap.suite.ui.commons.HeaderContainer.prototype.removeAggregation=function(a,o,s){return this._callMethodInManagedObject("removeAggregation",a,o,s)};
sap.suite.ui.commons.HeaderContainer.prototype.removeAllAggregation=function(a,s){return this._callMethodInManagedObject("removeAllAggregation",a,s)};
sap.suite.ui.commons.HeaderContainer.prototype.destroyAggregation=function(a,s){this._callMethodInManagedObject("destroyAggregation",a,s);return this};
