/*!
 * SAP UI development toolkit for HTML5 (SAPUI5) (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.suite.ui.commons.ProcessFlowLaneHeader");jQuery.sap.require("sap.suite.ui.commons.library");jQuery.sap.require("sap.ui.core.Control");sap.ui.core.Control.extend("sap.suite.ui.commons.ProcessFlowLaneHeader",{metadata:{library:"sap.suite.ui.commons",properties:{"text":{type:"string",group:"Misc",defaultValue:null},"iconSrc":{type:"sap.ui.core.URI",group:"Misc",defaultValue:null},"position":{type:"int",group:"Misc",defaultValue:null},"laneId":{type:"string",group:"Misc",defaultValue:null},"state":{type:"object",group:"Misc",defaultValue:null},"zoomLevel":{type:"sap.suite.ui.commons.ProcessFlowZoomLevel",group:"Misc",defaultValue:null}},events:{"press":{}}}});sap.suite.ui.commons.ProcessFlowLaneHeader.M_EVENTS={'press':'press'};jQuery.sap.require("sap.ui.core.IconPool");jQuery.sap.require("sap.m.Image");
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype.init=function(){this._virtualTableSpan=1};
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype.onAfterRendering=function(){var t=this.$();var $=this.$("lh-icon");var c='click';if(sap.ui.Device.support.touch){c='touchend'}$.on(c,jQuery.proxy(this.ontouchend,this));$.addClass("suiteUiProcessFlowLaneHeaderProcessSymbolIcon");$.css("cursor","inherit");if(this._isHeaderMode()){t.addClass("suiteUiProcessFlowLaneHeaderPointer")}else{t.removeClass("suiteUiProcessFlowLaneHeaderPointer")}if(sap.ui.Device.browser.msie||sap.ui.Device.browser.mozilla){this.$("lh-text").css("word-break","break-all")}if(!this._ellipsisDisabled&&!sap.suite.ui.commons.ProcessFlowLaneHeader._hasNativeLineClamp){this._clampText()}};
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype.getSymbolType=function(){return this._oSymbolType?this._oSymbolType:sap.suite.ui.commons.ProcessFlowLaneHeader.symbolType.standardType};
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype._setSymbolType=function(s,o){o._oSymbolType=s};
sap.suite.ui.commons.ProcessFlowLaneHeader.createNewStartSymbol=function(h){var s=sap.suite.ui.commons.ProcessFlowLaneHeader,S=new sap.suite.ui.commons.ProcessFlowLaneHeader({laneId:"processFlowLaneStart"});S._setSymbolType(s.symbolType.startSymbol,S);S._setHeaderMode(h);return S};
sap.suite.ui.commons.ProcessFlowLaneHeader.createNewEndSymbol=function(h){var s=sap.suite.ui.commons.ProcessFlowLaneHeader,e=new sap.suite.ui.commons.ProcessFlowLaneHeader({laneId:"processFlowLaneEnd"});e._setSymbolType(s.symbolType.endSymbol,e);e._setHeaderMode(h);return e};
sap.suite.ui.commons.ProcessFlowLaneHeader.createNewProcessSymbol=function(h){var s=sap.suite.ui.commons.ProcessFlowLaneHeader,p=new sap.suite.ui.commons.ProcessFlowLaneHeader({laneId:"processFlowLaneProcess",iconSrc:"sap-icon://process"});p._setSymbolType(s.symbolType.processSymbol,p);p._setHeaderMode(h);return p};
sap.suite.ui.commons.ProcessFlowLaneHeader.symbolType={startSymbol:"startSymbol",endSymbol:"endSymbol",processSymbol:"processSymbol",standardType:"standardType"};sap.suite.ui.commons.ProcessFlowLaneHeader._constants={nHalfGapSize:0.0241,nMinPercentage:0.025,nRingThickness:5,nRingInnerRadius:24,nPositionX:32,nPositionY:32,nOuterCircleRadius:32,sOuterCircleColor:"#ffffff",sOuterCircleStrokeColor:"#dddddd",nOuterCircleStrokeWidth:1,sSectorPositiveColor:"#61a656",sSectorNegativeColor:"#d32030",sSectorNeutralColor:"#ffffff",sSectorPlannedColor:"#999999",sEllipsis:'...',nEllipsisLength:3};
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype._clampValues=function(p,n,a){var i=p.length-1,c=false,v;while(i>=0){v=p[i];if(v<n){p[i]=a;c=true}i--}return c};
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype._rescaleToUnit=function(p,a){var s,i,n,m,v,f;if(!a){a=0}i=p.length-1;s=0;n=m=0;while(i>=0){v=p[i];if(v>0){if(v<=a){m++}else{s+=p[i]}n++}i--}s-=(n-m)*a;f=(1-n*a)/s;i=p.length-1;while(i>=0){v=p[i];if(v>0){p[i]=(v<=a)?a:((v-a)*f+a)}i--}};
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype._countGaps=function(p){var i=p.length-1,n=0;while(i>=0){if(p[i]>0){n++}i--}if(n===1){n=0}return n};
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype._rescaleByFactor=function(p,n){var i=p.length-1;while(i>=0){p[i]*=n;i--}};
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype._colorMap=[sap.suite.ui.commons.ProcessFlowLaneHeader._constants.sSectorPositiveColor,sap.suite.ui.commons.ProcessFlowLaneHeader._constants.sSectorNegativeColor,sap.suite.ui.commons.ProcessFlowLaneHeader._constants.sSectorPlannedColor,sap.suite.ui.commons.ProcessFlowLaneHeader._constants.sSectorNeutralColor];
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype._calculateSectorRangeDefinitions=function(p,n){var d=[],b=-Math.PI/2,e,m=p.length,i=0;while(i<m){if(p[i]>0){e=b+2*Math.PI*p[i];d.push({start:b,end:e,color:this._colorMap[i]});b=e+n}i++}return d};
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype._selectColor=function(p){var c;if(p[0]){c=sap.suite.ui.commons.ProcessFlowLaneHeader._constants.sSectorPositiveColor}else if(p[1]){c=sap.suite.ui.commons.ProcessFlowLaneHeader._constants.sSectorNegativeColor}else if(p[2]){c=sap.suite.ui.commons.ProcessFlowLaneHeader._constants.sSectorPlannedColor}else{c=sap.suite.ui.commons.ProcessFlowLaneHeader._constants.sSectorNeutralColor}return c};
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype._renderDonutPercentages=function(r){var s=this.getState(),n=0,S,p=[0,0,0,0],a,c,b=sap.suite.ui.commons.ProcessFlowLaneHeader._constants.nHalfGapSize,d=sap.suite.ui.commons.ProcessFlowLaneHeader._constants.nRingInnerRadius,e=sap.suite.ui.commons.ProcessFlowLaneHeader._constants.nRingThickness,f=sap.suite.ui.commons.ProcessFlowLaneHeader._constants.nRingInnerRadius+e,o=sap.suite.ui.commons.ProcessFlowLaneHeader._constants.sOuterCircleColor,O=sap.suite.ui.commons.ProcessFlowLaneHeader._constants.sOuterCircleStrokeColor,g=sap.suite.ui.commons.ProcessFlowLaneHeader._constants.nOuterCircleStrokeWidth,h=sap.suite.ui.commons.ProcessFlowLaneHeader._constants.nOuterCircleRadius,i=sap.suite.ui.commons.ProcessFlowLaneHeader._constants.nPositionX,j=sap.suite.ui.commons.ProcessFlowLaneHeader._constants.nPositionY,k=sap.suite.ui.commons.ProcessFlowLaneHeader._constants.nMinPercentage;if(s&&Object.prototype.toString.call(s)==='[object Array]'&&(s.length>0)){s.forEach(function(l){switch(l.state){case sap.suite.ui.commons.ProcessFlowNodeState.Positive:p[0]=l.value;break;case sap.suite.ui.commons.ProcessFlowNodeState.Negative:p[1]=l.value;break;case sap.suite.ui.commons.ProcessFlowNodeState.Planned:p[2]=l.value;break;case sap.suite.ui.commons.ProcessFlowNodeState.Neutral:default:p[3]=l.value}});this._clampValues(p,0,0);this._rescaleToUnit(p);this._rescaleToUnit(p,k);n=this._countGaps(p);a=(1-n*b/Math.PI);this._rescaleByFactor(p,a);this._renderCircle(r,o,O,g,i,j,h);if(n>0){S=this._calculateSectorRangeDefinitions(p,2*b);this._renderDonutSectors(r,S,i,j,d,f)}else{c=this._selectColor(p);this._renderCircle(r,o,c,e,i,j,d+e/2)}}else{this._renderCircle(r,o,O,g,i,j,h)}};
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype._renderCircle=function(r,c,s,n,a,b,d){r.write("<circle");r.writeAttribute("id",this.getId()+"-donut-circle");r.writeAttribute("fill",c);r.writeAttribute("stroke",s);r.writeAttribute("stroke-width",n);r.writeAttribute("cx",a);r.writeAttribute("cy",b);r.writeAttribute("r",d);r.write("></circle>")};
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype._renderDonutSectors=function(r,s,n,a,b,c){var i=0,d=s.length,S,p;while(i<d){S=s[i];p=this._getDonutSectorPath(n,a,S.start,S.end,b,c);r.write("<path");r.writeAttribute("id",this.getId()+"-donut-segment-"+i);r.writeAttribute("d",p);r.writeAttribute("fill",S.color);r.writeAttribute("opacity","1");r.write("></path>");i++}};
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype._getDonutSectorPath=function(n,a,b,c,e,f){var g=0,p,h,i,j,d,k,l,s,m;if((c-b)%(Math.PI*2)>Math.PI){g=1}k=Math.cos(b);l=Math.cos(c);s=Math.sin(b);m=Math.sin(c);p=(n+e*k).toFixed(3)+','+(a+e*s).toFixed(3);h=(n+f*k).toFixed(3)+','+(a+f*s).toFixed(3);i=(n+f*l).toFixed(3)+','+(a+f*m).toFixed(3);j=(n+e*l).toFixed(3)+','+(a+e*m).toFixed(3);d="M"+p+"L"+h+"A"+f+','+f+" 0 "+g+" 1 "+i+"L"+j+"A"+e+','+e+" 0 "+g+" 0 "+p+"z";return d};
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype._getImage=function(i,s){this._destroyImage();if(this._oImageControl){this._oImageControl.setSrc(s)}else{this._oImageControl=sap.ui.core.IconPool.createControlByURI(s,sap.m.Image);this._oImageControl.sId=i;this._oImageControl.setParent(this,null,true)}return this._oImageControl};
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype.exit=function(){this._destroyImage()};
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype._destroyImage=function(){if(this._oImageControl){this._oImageControl.destroy()}this._oImageControl=null};
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype.ontouchend=function(e){if(e&&!e.isDefaultPrevented()){e.preventDefault()}if(this){this.firePress(this)}if(e&&!e.isPropagationStopped()){e.stopPropagation()}if(e&&!e.isImmediatePropagationStopped()){e.stopImmediatePropagation()}};
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype._setHeaderMode=function(h){this._bHeaderMode=h};
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype._isHeaderMode=function(){return this._bHeaderMode};
sap.suite.ui.commons.ProcessFlowLaneHeader.prototype._clampText=function(){var $=this.$("lh-text").length?this.$("lh-text"):null,t=this.getText(),l="",e=sap.suite.ui.commons.ProcessFlowLaneHeader._constants.sEllipsis,E=sap.suite.ui.commons.ProcessFlowLaneHeader._constants.nEllipsisLength,s=E+1,m,i=t.length,M,v;if($){M=parseInt($.css("height").slice(0,-2),10);if($[0].scrollHeight>M){v=$.css("visibility");$.css("visibility","hidden");l=t;do{m=(s+i)>>1;$.textContent=t.slice(0,m-E)+e;if($.scrollHeight>M){i=m}else{s=m;l=$.textContent}}while(i-s>1);$.css("visibility",v)}if($.scrollHeight>M){$.textContent=l}}};
sap.suite.ui.commons.ProcessFlowLaneHeader._hasNativeLineClamp=(function(){return document.documentElement.style.webkitLineClamp!==undefined}());
sap.suite.ui.commons.ProcessFlowLaneHeader.enableEllipsisSupportForText=function(s){this._ellipsisDisabled=!s};
sap.suite.ui.commons.ProcessFlowLaneHeader._setVirtualTableSpan=function(e){this._virtualTableSpan=e};
sap.suite.ui.commons.ProcessFlowLaneHeader._getVirtualTableSpan=function(){return this._virtualTableSpan};
