/*!
 * SAP UI development toolkit for HTML5 (SAPUI5) (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.suite.ui.commons.TimelineItem");jQuery.sap.require("sap.suite.ui.commons.library");jQuery.sap.require("sap.ui.core.Control");sap.ui.core.Control.extend("sap.suite.ui.commons.TimelineItem",{metadata:{library:"sap.suite.ui.commons",properties:{"dateTime":{type:"any",group:"Misc",defaultValue:null},"userName":{type:"string",group:"Misc",defaultValue:null},"title":{type:"string",group:"Misc",defaultValue:null},"text":{type:"string",group:"Misc",defaultValue:null},"icon":{type:"string",group:"Misc",defaultValue:null},"filterValue":{type:"string",group:"Misc",defaultValue:null},"userNameClickable":{type:"boolean",group:"Misc",defaultValue:false}},aggregations:{"embeddedControl":{type:"sap.ui.core.Control",multiple:false}},events:{"userNameClicked":{}}}});sap.suite.ui.commons.TimelineItem.M_EVENTS={'userNameClicked':'userNameClicked'};jQuery.sap.require("sap.m.library");jQuery.sap.require("sap.ui.core.IconPool");jQuery.sap.require("sap.ui.core.format.DateFormat");
sap.suite.ui.commons.TimelineItem.prototype.init=function(){var l=sap.ui.getCore().getConfiguration().getLanguage();this.resBundle=sap.ui.getCore().getLibraryResourceBundle("sap.suite.ui.commons",l);this._showIcons=false};
sap.suite.ui.commons.TimelineItem.prototype._formatDateValue=function(d){var D;if(d instanceof Date){D=d}else if(typeof d==="string"){if(d.indexOf("Date")!=-1){var i=d.substring(d.indexOf("(")+1,d.indexOf(")"));D=new Date(parseInt(i))}}else{D=new Date(parseInt(d))}var r="";var a=0,t,T=new Date();var c=T.getFullYear();var b=T.getMonth();var e=T.getDate();var f=D.getFullYear();var g=D.getMonth();var h=D.getDate();var j=Date.UTC(c,b,e);var k=Date.UTC(f,g,h);t=j.valueOf()-k.valueOf();a=Math.floor(t/(24*60*60*1000));var l=sap.ui.core.format.DateFormat.getDateInstance({style:"short"});var m=sap.ui.core.format.DateFormat.getTimeInstance({style:"short"});if(a==0){r=this.resBundle.getText('TIMELINE_TODAY')}else if(a==1){r=this.resBundle.getText('TIMELINE_YESTERDAY')}else if(a>1){r=l.format(D)}else{return D.toString()}r+=" "+this.resBundle.getText('TIMELINE_AT')+" "+m.format(D);return r};
sap.suite.ui.commons.TimelineItem.prototype._getImageControl=function(){var i=this.getIcon()?this.getIcon():"activity-items";var I=this.getId()+'-icon';var p={src:i};var c=['sapSuiteUiCommonsTimelineItemIcon'];this._oImageControl=sap.m.ImageHelper.getImageControl(I,this._oImageControl,this,p,c);return this._oImageControl};
sap.suite.ui.commons.TimelineItem.prototype._isOfTypeTimelineItem=function(){return true};
sap.suite.ui.commons.TimelineItem.prototype.setLayout=function(p,a){this._position=p;this._alignment=a};
sap.suite.ui.commons.TimelineItem.prototype.setUserNameClickable=function(u){this.setProperty("userNameClickable",u,true);if(!this._userNameLink){var t=this;this._userNameLink=new sap.m.Link({text:this.getUserName(),press:function(e){t.fireUserNameClicked()}})}};
sap.suite.ui.commons.TimelineItem.prototype.onBeforeRendering=function(){if(this.getUserNameClickable()&&(!this._userNameLink)){var t=this;this._userNameLink=new sap.m.Link({text:this.getUserName(),press:function(e){t.fireUserNameClicked()}})}};
sap.suite.ui.commons.TimelineItem.prototype.exit=function(){if(this._oImageControl){this._oImageControl.destroy();this._oImageControl=undefined}if(this._userNameLink){this._userNameLink.destroy();this._userNameLink=undefined}};
